export const provinceData = [
  {
    province: 'Adana',
    districts: [
      'Seyhan',
      'Yüreğir',
      'Çukurova',
      'Sarıçam',
      'Kozan',
      'Ceyhan',
      'Feke',
      'Pozantı',
      'Aladağ',
      'Tufanbeyli',
      'Saimbeyli',
      'Yumurtalık',
    ],
  },
  {
    province: 'Adıyaman',
    districts: [
      'Besni',
      'Gölbaşı',
      'Kahta',
      'Merkez',
      'Çelikhan',
      'Gerger',
      'Samsat',
      'Tut',
    ],
  },
  {
    province: 'Afyonkarahisar',
    districts: [
      'Merkez',
      'Bolvadin',
      'Çay',
      'Dazkırı',
      'Sandıklı',
      'Sınav',
      'İhsaniye',
      'Emirdağ',
      'Şuhut',
    ],
  },
  {
    province: 'Ağrı',
    districts: [
      'Merkez',
      'Doğubayazıt',
      'Diyadin',
      'Eleşkirt',
      'Hamur',
      'Patnos',
      'Tutak',
    ],
  },
  {
    province: 'Aksaray',
    districts: [
      'Merkez',
      'Ağaçören',
      'Eskil',
      'Güzelyurt',
      'Kızılkaya',
      'Ortaköy',
      'Sarıyahşi',
    ],
  },
  {
    province: 'Amasya',
    districts: [
      'Merkez',
      'Göynücek',
      'Hamamözü',
      'Merzifon',
      'Suluova',
      'Taşova',
    ],
  },
  {
    province: 'Ankara',
    districts: [
      'Çankaya',
      'Keçiören',
      'Yenimahalle',
      'Mamak',
      'Sincan',
      'Etimesgut',
      'Gölbaşı',
      'Polatlı',
      'Akyurt',
      'Bala',
      'Çubuk',
      'Elmadağ',
      'Güdül',
      'Haymana',
      'Kızılcahamam',
      'Nallıhan',
      'Pursaklar',
      'Şereflikoçhisar',
      'Kalecik',
      'Çamlıdere',
    ],
  },
  {
    province: 'Antalya',
    districts: [
      'Muratpaşa',
      'Kepez',
      'Konyaaltı',
      'Alanya',
      'Kemer',
      'Döşemealtı',
      'Finike',
      'Gazipaşa',
      'Kalkan',
      'Kaş',
      'Kumluca',
      'Serik',
      'Demre',
      'İbradı',
      'Gündoğmuş',
      'Aksu',
    ],
  },
  {
    province: 'Artvin',
    districts: [
      'Merkez',
      'Arhavi',
      'Hopa',
      'Kemalpaşa',
      'Murgul',
      'Şavşat',
      'Yusufeli',
      'Borçka',
    ],
  },
  {
    province: 'Aydın',
    districts: [
      'Merkez',
      'Efeler',
      'Nazilli',
      'Söke',
      'Kuşadası',
      'Didim',
      'Buharkent',
      'Çine',
      'Germencik',
      'Karacasu',
      'Karpuzlu',
      'Koçarlı',
      'Latifli',
    ],
  },
  {
    province: 'Balıkesir',
    districts: [
      'Merkez',
      'Ayvalık',
      'Burhaniye',
      'Dursunbey',
      'Edremit',
      'Erdek',
      'Gömeç',
      'Karesi',
      'Sındırgı',
      'Susurluk',
    ],
  },
  {
    province: 'Bilecik',
    districts: [
      'Merkez',
      'Bozüyük',
      'Pazaryeri',
      'Söğüt',
      'Osmaneli',
      'İnhisar',
    ],
  },
  {
    province: 'Bingöl',
    districts: ['Merkez', 'Genç', 'Kiğı', 'Solhan', 'Yayladere', 'Adaklı'],
  },
  {
    province: 'Bitlis',
    districts: ['Merkez', 'Ahlat', 'Tatvan', 'Hizan', 'Güroymak', 'Adilcevaz'],
  },
  {
    province: 'Bolu',
    districts: [
      'Merkez',
      'Gerede',
      'Göynük',
      'Dörtdivan',
      'Mudurnu',
      'Seben',
      'Yeniçağa',
    ],
  },
  {
    province: 'Burdur',
    districts: [
      'Merkez',
      'Ağlasun',
      'Bucak',
      'Çavdır',
      'Gölhisar',
      'Karamanlı',
      'Tefenni',
      'Altınyayla',
    ],
  },
  {
    province: 'Bursa',
    districts: [
      'Merkez',
      'Osmangazi',
      'Nilüfer',
      'Gemlik',
      'Mudanya',
      'Yıldırım',
      'Karacabey',
      'İnegöl',
      'Orhangazi',
      'Mustafakemalpaşa',
      'Büyükorhan',
    ],
  },
  {
    province: 'Çanakkale',
    districts: [
      'Merkez',
      'Biga',
      'Çan',
      'Eceabat',
      'Ezine',
      'Gelibolu',
      'Lapseki',
      'Ayvacık',
      'Bayramiç',
      'Gökçeada',
      'Bozcaada',
    ],
  },
  {
    province: 'Çankırı',
    districts: [
      'Merkez',
      'Atkaracalar',
      'Çerkeş',
      'Eldivan',
      'Korgun',
      'Orta',
      'Şabanözü',
      'Ilgaz',
      'Karaburun',
    ],
  },
  {
    province: 'Denizli',
    districts: [
      'Merkez',
      'Acıpayam',
      'Babadağ',
      'Baklan',
      'Beyağaç',
      'Çal',
      'Çameli',
      'Güney',
      'Pamukkale',
      'Serinhisar',
      'Tavas',
    ],
  },
  {
    province: 'Diyarbakır',
    districts: [
      'Merkez',
      'Bağlar',
      'Kayapınar',
      'Sur',
      'Yenişehir',
      'Çınar',
      'Ergani',
      'Hani',
      'Lice',
      'Silvan',
      'Bismil',
      'Kulp',
    ],
  },
  {
    province: 'Edirne',
    districts: [
      'Merkez',
      'Keşan',
      'Enez',
      'Lalapaşa',
      'Meriç',
      'Uzunköprü',
      'Havsa',
      'Süloğlu',
    ],
  },
  {
    province: 'Elazığ',
    districts: [
      'Merkez',
      'Ağın',
      'Baskil',
      'Karakoçan',
      'Keban',
      'Maden',
      'Palu',
      'Sivrice',
      'Tunceli',
    ],
  },
  {
    province: 'Erzincan',
    districts: [
      'Merkez',
      'Çayırlı',
      'İliç',
      'Kemaliye',
      'Otlukbeli',
      'Refahiye',
      'Tercan',
      'Üzümlü',
    ],
  },
  {
    province: 'Erzurum',
    districts: [
      'Merkez',
      'Aşkale',
      'Aziziye',
      'Horasan',
      'İspir',
      'Oltu',
      'Palandöken',
      'Pasinler',
      'Pazaryolu',
      'Şenkaya',
      'Tekman',
    ],
  },
  {
    province: 'Eskişehir',
    districts: [
      'Merkez',
      'Alpu',
      'Bütünpınar',
      'Germiyanoğlu',
      'Han',
      'Mihalıççık',
      'Odunpazarı',
      'Tepebaşı',
    ],
  },
  {
    province: 'Gaziantep',
    districts: [
      'Merkez',
      'Şahinbey',
      'Oğuzeli',
      'Nizip',
      'Araban',
      'Karkamış',
      'Yavuzeli',
    ],
  },
  {
    province: 'Giresun',
    districts: [
      'Merkez',
      'Alucra',
      'Bulancak',
      'Dereli',
      'Doğankent',
      'Espiye',
      'Eynesil',
      'Giresun',
      'Görele',
      'Keşap',
      'Piraziz',
      'Tirebolu',
      'Yağlıdere',
    ],
  },
  {
    province: 'Gümüşhane',
    districts: [
      'Merkez',
      'Kelkit',
      'Köse',
      'Torul',
      'Şiran',
      'Hakcılar',
      'Merkez',
    ],
  },
  {
    province: 'Hakkari',
    districts: ['Merkez', 'Çukurca', 'Hakkari', 'Şemdinli', 'Yüksekova'],
  },
  {
    province: 'Hatay',
    districts: [
      'Antakya',
      'Defne',
      'Dörtyol',
      'Erzin',
      'Hassa',
      'İskenderun',
      'Kaman',
      'Reyhanlı',
      'Samandağ',
      'Dörtyol',
    ],
  },
  {
    province: 'Iğdır',
    districts: ['Merkez', 'Aralık', 'Karakoyunlu', 'Tuzluca'],
  },
  {
    province: 'İstanbul',
    districts: [
      'Adalar',
      'Arnavutköy',
      'Ataşehir',
      'Bağcılar',
      'Bahçelievler',
      'Bakırköy',
      'Başakşehir',
      'Beykoz',
      'Beyoğlu',
      'Büyükçekmece',
      'Çatalca',
      'Çekmeköy',
      'Esenler',
      'Esenyurt',
      'Eyüp',
      'Fatih',
      'Gaziosmanpaşa',
      'Güngören',
      'Kadıköy',
      'Kartal',
      'Küçükçekmece',
      'Maltepe',
      'Pendik',
      'Sancaktepe',
      'Sarıyer',
      'Silivri',
      'Sultanbeyli',
      'Şile',
      'Şişli',
      'Tuzla',
      'Ümraniye',
      'Üsküdar',
      'Zeytinburnu',
    ],
  },
  {
    province: 'İzmir',
    districts: [
      'Aliağa',
      'Bayraklı',
      'Bergama',
      'Bornova',
      'Buca',
      'Çeşme',
      'Dikili',
      'Foça',
      'Gaziemir',
      'Güzelbahçe',
      'Karşıyaka',
      'Kemalpaşa',
      'Konak',
      'Menemen',
      'Narlıdere',
      'Seferihisar',
      'Tire',
      'Urla',
    ],
  },
  {
    province: 'Kahramanmaraş',
    districts: [
      'Merkez',
      'Andırın',
      'Dulkadiroğlu',
      'Elbistan',
      'Göksun',
      'Pazarcık',
      'Türkoğlu',
    ],
  },
  {
    province: 'Karabük',
    districts: ['Merkez', 'Eflani', 'Ovacık', 'Safranbolu', 'Yenice'],
  },
  {
    province: 'Kars',
    districts: ['Merkez', 'Arpaçay', 'Digor', 'Kağızman', 'Sarıkamış', 'Susuz'],
  },
  {
    province: 'Kastamonu',
    districts: [
      'Merkez',
      'Ağlı',
      'Araç',
      'Daday',
      'Devrekani',
      'Hanönü',
      'İnebolu',
      'Kastamonu',
      'Küre',
      'Pınarbaşı',
      'Şenpazar',
      'Sırtköy',
      'Taşköprü',
      'Tosya',
    ],
  },
  {
    province: 'Kayseri',
    districts: [
      'Merkez',
      'Bünyan',
      'Develi',
      'Felahiye',
      'Hacılar',
      'İncesu',
      'Kocasinan',
      'Melikgazi',
      'Özvatan',
      'Talas',
      'Talas',
      'Yeşilhisar',
    ],
  },
  {
    province: 'Kırıkkale',
    districts: [
      'Merkez',
      'Bahşili',
      'Balışeyh',
      'Delice',
      'Karakeçili',
      'Keskin',
      'Sülük',
      'Yahşihan',
    ],
  },
  {
    province: 'Kırklareli',
    districts: [
      'Merkez',
      'Babaeski',
      'Demirköy',
      'Kofçaz',
      'Lüleburgaz',
      'Pınarhisar',
      'Vize',
    ],
  },
  {
    province: 'Kırşehir',
    districts: [
      'Merkez',
      'Akçakent',
      'Akpınar',
      'Boztepe',
      'Çiçekdağı',
      'Kaman',
      'Mucur',
    ],
  },
  {
    province: 'Kocaeli',
    districts: [
      'Başiskele',
      'Çayırova',
      'Darıca',
      'Dilovası',
      'Gölcük',
      'Kandıra',
      'Karamürsel',
      'Merkez',
      'Sebze',
      'Sakarya',
      'Tuzla',
      'Gölcük',
    ],
  },
  {
    province: 'Konya',
    districts: [
      'Merkez',
      'Ahırlı',
      'Akşehir',
      'Akören',
      'Beyşehir',
      'Bozkır',
      'Çumra',
      'Derbent',
      'Doğanhisar',
      'Ereğli',
      'Güneysınır',
      'Halkapınar',
      'Ilgın',
      'Karapınar',
      'Karatay',
      'Selçuklu',
      'Seydişehir',
      'Tuzlukçu',
      'Yunak',
    ],
  },
  {
    province: 'Kütahya',
    districts: [
      'Merkez',
      'Altıntaş',
      'Aslanapa',
      'Domanic',
      'Hisarcık',
      'Pazarlar',
      'Simav',
      'Tavşanlı',
      'Gediz',
    ],
  },
  {
    province: 'Malatya',
    districts: [
      'Merkez',
      'Battalgazi',
      'Doğanşehir',
      'Hekimhan',
      'Kale',
      'Pütürge',
      'Yeşilyurt',
    ],
  },
  {
    province: 'Manisa',
    districts: [
      'Merkez',
      'Akhisar',
      'Demirci',
      'Gördes',
      'Kula',
      'Salihli',
      'Sarıgöl',
      'Selendi',
      'Turgutlu',
      'Ahmetli',
      'Köprübaşı',
      'Şehzadeler',
    ],
  },
  {
    province: 'Mardin',
    districts: [
      'Merkez',
      'Artuklu',
      'Dargeçit',
      'Kızıltepe',
      'Nusaybin',
      'Savur',
      'Dargeçit',
    ],
  },
  {
    province: 'Mersin',
    districts: [
      'Merkez',
      'Akdeniz',
      'Anamur',
      'Bozyazı',
      'Erdemli',
      'Gülnar',
      'Tarsus',
      'Çamlıyayla',
    ],
  },
  {
    province: 'Muğla',
    districts: [
      'Bodrum',
      'Dalaman',
      'Datça',
      'Fethiye',
      'Köyceğiz',
      'Marmaris',
      'Muğla',
      'Ortaca',
      'Dalaman',
      'Seydikemer',
    ],
  },
  {
    province: 'Nevşehir',
    districts: [
      'Avanos',
      'Derinkuyu',
      'Gülşehir',
      'Hacıbektaş',
      'Merkez',
      'Ürgüp',
    ],
  },
  {
    province: 'Niğde',
    districts: ['Merkez', 'Bor', 'Çamardı', 'Ulukışla'],
  },
  {
    province: 'Ordu',
    districts: [
      'Merkez',
      'Altınordu',
      'Gölköy',
      'Gürgentepe',
      'Kabadüz',
      'Kabataş',
      'Perşembe',
      'Ünye',
    ],
  },
  {
    province: 'Rize',
    districts: [
      'Merkez',
      'Ardeşen',
      'Çamlıhemşin',
      'Derepazarı',
      'Fındıklı',
      'İkizdere',
      'Pazar',
      'Rize',
      'Salarha',
      'Ayder',
    ],
  },
  {
    province: 'Sakarya',
    districts: [
      'Adapazarı',
      'Akyazı',
      'Arifiye',
      'Erenler',
      'Ferizli',
      'Hendek',
      'Karasu',
      'Sapanca',
      'Serdivan',
      'Pamukova',
      'Karla',
    ],
  },
  {
    province: 'Samsun',
    districts: [
      'Merkez',
      'Alaçam',
      'Bafra',
      'Canik',
      'Çarşamba',
      'Kavak',
      'Ladik',
      'Salıpazarı',
      'Tekkeköy',
      'Vezirköprü',
      'Yakakent',
    ],
  },
  {
    province: 'Siirt',
    districts: [
      'Merkez',
      'Baykan',
      'Bitan',
      'Eruh',
      'Kurtalan',
      'Pervari',
      'Tillo',
    ],
  },
  {
    province: 'Sinop',
    districts: [
      'Merkez',
      'Ayancık',
      'Boyabat',
      'Durağan',
      'Gerze',
      'Saraydüzü',
      'Türkeli',
    ],
  },
  {
    province: 'Sivas',
    districts: [
      'Merkez',
      'Akıncılar',
      'Gölova',
      'Kangal',
      'Zara',
      'Divriği',
      'Doğanşar',
      'Gemerek',
      'Şarkışla',
    ],
  },
  {
    province: 'Tekirdağ',
    districts: [
      'Merkez',
      'Çerkezköy',
      'Ergene',
      'Hayrabolu',
      'Malkara',
      'Marmara Ereğlisi',
      'Saray',
      'Şarköy',
    ],
  },
  {
    province: 'Tokat',
    districts: [
      'Merkez',
      'Almus',
      'Artova',
      'Büyükkışla',
      'Erbaa',
      'Niksar',
      'Reşadiye',
      'Turhal',
      'Zile',
    ],
  },
  {
    province: 'Trabzon',
    districts: [
      'Merkez',
      'Akçaabat',
      'Araklı',
      'Arsin',
      'Beşikdüzü',
      'Çaykara',
      'Düzköy',
      'Hayrat',
      'Of',
      'Sürmene',
      'Tonya',
      'Yomra',
    ],
  },
  {
    province: 'Tunceli',
    districts: [
      'Merkez',
      'Çemişgezek',
      'Hozat',
      'Mazgirt',
      'Nazımiye',
      'Pertek',
      'Pülümür',
      'Tunceli',
    ],
  },
  {
    province: 'Uşak',
    districts: ['Merkez', 'Banaz', 'Eşme', 'Karahallı', 'Sivaslı'],
  },
  {
    province: 'Van',
    districts: [
      'Merkez',
      'Başkale',
      'Çaldıran',
      'Çatak',
      'Edremit',
      'Erciş',
      'Gevaş',
      'Gürpınar',
      'Muradiye',
      'Sondak',
    ],
  },
  {
    province: 'Yalova',
    districts: ['Merkez', 'Altınova', 'Çınarcık', 'Termal', 'Armutlu'],
  },
  {
    province: 'Yozgat',
    districts: [
      'Merkez',
      'Akdağmadeni',
      'Boğazlıyan',
      'Çekerek',
      'Dolunay',
      'Sorgun',
      'Yozgat',
      'Sarıkaya',
    ],
  },
  {
    province: 'Zonguldak',
    districts: [
      'Merkez',
      'Alaplı',
      'Çaycuma',
      'Devrek',
      'Ereğli',
      'Gökçebey',
      'Kilimli',
      'Zonguldak',
    ],
  },
];
